// [
//   { label: "项目名称", field: "projectName", type: "input", width: "33%", required: true, },
//   {
//     label: "项目立项日期",
//     field: "approvalDate",
//     type: "date",
//     width: "33%",
//     required: true,
//   },
//   {
//     label: "申请人",
//     field: "purchaseSubUserId",
//     required: true,
//     type: "selectinput",
//     source: "applicantList",
//     width: "33%",
//   },
//   {
//     label: "立项部门",
//     field: "purchaseDeptId",
//     required: true,
//     type: "selectinput",
//     source: "adepartmentList",
//     width: "33%",
//   },
//   {
//     label: "采购预算金额",
//     field: "amount",
//     type: "",
//     digits: 2,
//     precision: 2,
//     formatterName: "toFixedNumber",
//     width: "33%",
//   },
//   {
//     label: "采购申请说明",
//     field: "purchaseRequestDescription",
//     type: "textarea",
//     width: "33%",
//   },
//   {
//     label: "寻源方式",
//     field: "sourcingMethod",
//     required: true,
//     type: "selectinput",
//     source: "sourcingMethodList",
//     width: "33%",
//   },
//   {
//     label: "标段",
//     field: "isBidSegment",
//     type: "radio",
//     source: "lotList",
//     width: "33%",
//   },
//   { label: "数据来源", field: "dataSourceName", type: "", width: "33%" },
// ];

// [
//   {
//     title: "选择",
//     type: "checkbox",
//     width: "80",
//     align: "center",
//     resizable: "true",
//     minWidth: "80",
//     visible: "true",
//   },
//   {
//     field: "rowNum",
//     title: "序号",
//     width: "80",
//     align: "center",
//     resizable: "true",
//     slots: { default: "rowNum" },
//     minWidth: "80",
//     visible: "true",
//   },
//   {
//     field: "materialName",
//     title: "采购商品",
//     width: 190,
//     minWidth: 70,
//     resizable: false,
//     align: "left",
//     sortable: true,
//     visible: true,
//   },
//   {
//     field: "materialTypeName",
//     title: "物料类型",
//     width: 190,
//     minWidth: 70,
//     resizable: false,
//     align: "left",
//     sortable: true,
//     visible: true,
//   },
//   {
//     field: "materialCode",
//     title: "物料编码",
//     width: 190,
//     minWidth: 70,
//     resizable: false,
//     align: "left",
//     sortable: true,
//     visible: true,
//   },
//   {
//     field: "model",
//     title: "型号",
//     width: 190,
//     minWidth: 70,
//     resizable: false,

//     align: "left",
//     sortable: true,
//     visible: true,
//   },
//   {
//     field: "standard",
//     title: "规格",
//     width: 190,
//     minWidth: 70,
//     resizable: false,

//     align: "left",
//     sortable: true,
//     visible: true,
//   },
//   {
//     field: "voltageLevel",
//     title: "电压",
//     width: 190,
//     minWidth: 70,
//     resizable: false,

//     align: "left",
//     sortable: true,
//     visible: true,
//   },
//   {
//     field: "attribute",
//     title: "属性",
//     width: 190,
//     minWidth: 70,
//     resizable: false,

//     align: "left",
//     sortable: true,
//     visible: true,
//   },
//   {
//     field: "unit",
//     title: "单位",
//     width: 190,
//     minWidth: 70,
//     resizable: false,

//     align: "left",
//     sortable: true,
//     visible: true,
//   },
//   {
//     field: "qty",
//     title: "申请数量",
//     width: 190,
//     minWidth: 70,
//     resizable: false,
//     align: "left",
//     sortable: true,
//     visible: true,
//     slots: { default: "slot_edit_integerNumber" },
//   },
//   {
//     field: "untaxPrice",
//     title: "预算单价(不含税)",
//     width: 190,
//     minWidth: 70,
//     resizable: false,

//     align: "left",
//     sortable: true,
//     visible: true,
//   },
//   {
//     field: "taxRate",
//     title: "税率",
//     width: 190,
//     minWidth: 70,
//     resizable: false,

//     align: "left",
//     sortable: true,
//     visible: true,
//     params: {
//       displayDigits: 2,
//     },
//     slots: { default: "slot_edit_number" },
//   },
//   {
//     field: "price",
//     title: "预算单价(含税)",
//     width: 190,
//     minWidth: 70,
//     resizable: false,
//     params: {
//       displayDigits: 2,
//     },
//     align: "left",
//     sortable: true,
//     visible: true,
//   },
//   {
//     field: "untaxAmount",
//     title: "预算金额(不含税)",
//     width: 190,
//     minWidth: 70,
//     resizable: false,
//     params: {
//       displayDigits: 2,
//     },
//     align: "left",
//     sortable: true,
//     visible: true,
//   },
//   {
//     field: "amount",
//     title: "预算金额(含税)",
//     width: 190,
//     minWidth: 70,
//     resizable: false,
//     params: {
//       displayDigits: 2,
//     },
//     align: "left",
//     sortable: true,
//     visible: true,
//   },
//   {
//     field: "latestArrivalDate",
//     title: "最晚到货时间",
//     width: 190,
//     minWidth: 70,
//     resizable: false,
//     align: "left",
//     sortable: true,
//     visible: true,
//     slots: { default: "slot_edit_date" },
//   },
// ];
// [
//   {
//     title: "选择",
//     type: "checkbox",
//     width: "80",
//     align: "center",
//     resizable: "true",
//     minWidth: "80",
//     visible: "true",
//   },
//   {
//     field: "rowNum",
//     title: "序号",
//     width: "80",
//     align: "center",
//     resizable: "true",
//     slots: { default: "rowNum" },
//     minWidth: "80",
//     visible: "true",
//   },
//   {
//     field: "bidSegmentCode",
//     title: "标段编码",
//     align: "center",
//     resizable: "true",
//     slots: { default: "slot_edit_input" },
//     minWidth: "80",
//     visible: "true",
//   },
//   {
//     field: "bidSegmentName",
//     title: "标段名称",
//     align: "center",
//     resizable: "true",
//     slots: { default: "slot_edit_input" },
//     minWidth: "80",
//     visible: "true",
//   },
//   {
//     field: "bidSegmentRemark",
//     title: "标段备注 ",
//     align: "center",
//     resizable: "true",
//     slots: { default: "slot_edit_input" },
//     minWidth: "80",
//     visible: "true",
//   },
//   {
//     field: "amount",
//     title: "标段预算",
//     align: "center",
//     resizable: "true",
//     params: {
//       displayDigits: 2,
//     },
//     slots: { default: "slot_edit_number" },
//     minWidth: "80",
//     visible: "true",
//   }
// ];
