[
  {
    field: "billNo",
    title: "流水号",
    width: 190,
    minWidth: 70,
    resizable: false,
    fixed: "left",
    align: "left",
    sortable: true,
    visible: true,
  },
  {
    field: "createUserName",
    title: "创建人",
    width: 160,
    minWidth: 70,
    align: "left",
    sortable: true,
  },
  {
    field: "createTime",
    title: "单据时间",
    width: 170,
    minWidth: 70,
    align: "left",
    sortable: true,
    visible: true,
  },
  {
    field: "submissionTime",
    title: "提交时间",
    width: 170,
    minWidth: 70,
    align: "left",
    sortable: true,
    visible: true,
  },
  {
    field: "auditDate",
    title: "审核时间",
    width: 170,
    minWidth: 70,
    align: "left",
    sortable: true,
    visible: true,
  },
  {
    field: "fromBillNo",
    title: "询价单号",
    width: 160,
    minWidth: 70,
    align: "left",
    sortable: true,
    visible: true,
  },
  {
    field: "quoteBillNo",
    title: "报价单号",
    width: 160,
    minWidth: 70,
    align: "left",
    sortable: true,
    visible: true,
  },
  {
    field: "xqbillno",
    title: "需求池流水号",
    width: 160,
    minWidth: 70,
    align: "left",
    sortable: true,
    visible: true,
  },
  {
    field: "gyscode",
    title: "供应商编码",
    width: 160,
    minWidth: 70,
    align: "left",
    sortable: true,
    visible: true,
  },
  {
    field: "projectName",
    title: "项目名称",
    width: 160,
    minWidth: 70,
    align: "left",
    sortable: true,
    visible: true,
  },
  {
    field: "gysname",
    title: "供应商名称",
    width: 160,
    minWidth: 70,
    align: "left",
    sortable: true,
    visible: true,
  },
  {
    field: "cgsqddh",
    title: "采购申请订单号",
    width: 160,
    minWidth: 70,
    align: "left",
    sortable: true,
    visible: true,
  },
  {
    field: "bjjztime",
    title: "报价截止时间",
    width: 160,
    minWidth: 70,
    align: "left",
    sortable: true,
    visible: true,
  },
  {
    field: "wpmc",
    title: "物品名称",
    width: 160,
    minWidth: 70,
    align: "left",
    sortable: true,
    visible: false,
  },
  {
    field: "aaa",
    title: "规格型号",
    width: 160,
    minWidth: 70,
    align: "left",
    sortable: true,
    visible: true,
  },
  {
    field: "xqqty",
    title: "需求数量",
    width: 160,
    minWidth: 70,
    align: "right",
    sortable: true,
    visible: true,
  },
  {
    field: "kghsl",
    title: "可供货数量",
    width: 160,
    minWidth: 70,
    align: "right",
    sortable: true,
    visible: true,
  },
  {
    field: "qprice",
    title: "报价单价(不含税)",
    width: 160,
    minWidth: 70,
    align: "right",
    sortable: true,
    visible: true,
  },
  {
    field: "rate",
    title: "税率",
    width: 160,
    minWidth: 70,
    align: "right",
    sortable: true,
    visible: true,
  },
  {
    field: "bjwyzd",
    title: "报价唯一辅助字段",
    width: 160,
    minWidth: 70,
    align: "left",
    sortable: true,
    visible: true,
  },
  {
    field: "cgsqbh",
    title: "采购申请编号",
    width: 160,
    minWidth: 70,
    align: "left",
    sortable: true,
    visible: true,
  },
  {
    field: "bcbjls",
    title: "本次询价轮次",
    width: 160,
    minWidth: 70,
    align: "left",
    sortable: true,
    visible: true,
  },
  {
    field: "cybj",
    title: "参与报价",
    width: 160,
    minWidth: 70,
    align: "left",
    sortable: true,
    visible: true,
  },
];
