[
  {
    field: "billNo",
    title: "流水号",
    width: 190,
    minWidth: 70,
    resizable: false,
    fixed: "left",
    align: "left",
    sortable: true,
    visible: true,
  },
  {
    field: "createUserName",
    title: "创建人",
    width: 160,
    minWidth: 70,
    align: "left",
    sortable: true,
  },
  {
    field: "createTime",
    title: "单据时间",
    width: 170,
    minWidth: 70,
    align: "left",
    sortable: true,
    visible: true,
  },

  {
    field: "submissionTime",
    title: "提交时间",
    width: 170,
    minWidth: 70,
    align: "left",
    sortable: true,
    visible: true,
  },
  {
    field: "auditDate",
    title: "审核时间",
    width: 170,
    minWidth: 70,
    align: "left",
    sortable: true,
    visible: true,
  },
  {
    field: "auditorName",
    title: "审核人",
    width: 160,
    minWidth: 70,
    align: "left",
    sortable: true,
    visible: true,
  },

  {
    field: "projectName",
    title: "招标项目名称",
    width: 160,
    minWidth: 70,
    align: "left",
    sortable: true,
    visible: true,
  },
  {
    field: "resultBillNo",
    title: "结果确认单号",
    width: 160,
    minWidth: 70,
    align: "left",
    sortable: true,
    visible: true,
  },
  {
    field: "enquiryBillNo",
    title: "询价单编号",
    width: 160,
    minWidth: 70,
    align: "left",
    sortable: true,
    visible: true,
  },
  {
    field: "quoteBillNo",
    title: "报价单号",
    width: 160,
    minWidth: 70,
    align: "left",
    sortable: true,
    visible: true,
  },
  {
    field: "currentEnquiryTimes",
    title: "报价轮数",
    width: 160,
    minWidth: 70,
    align: "right",
    sortable: true,
    visible: true,
  },

  {
    field: "businessLicense",
    title: "供应商名称",
    width: 160,
    minWidth: 70,
    align: "left",
    sortable: true,
    visible: true,
  },
  {
    field: "supplierBillNo",
    title: "供应商编码",
    width: 160,
    minWidth: 70,
    align: "left",
    sortable: true,
    visible: true,
  },
  {
    field: "materialName",
    title: "物品名称",
    width: 160,
    minWidth: 70,
    align: "left",
    sortable: true,
    visible: true,
  },
  {
    field: "standard",
    title: "规格",
    width: 160,
    minWidth: 70,
    align: "left",
    sortable: true,
    visible: true,
  },
  {
    field: "model",
    title: "型号",
    width: 160,
    minWidth: 70,
    align: "left",
    sortable: true,
    visible: true,
  },
  {
    field: "voltageLevel",
    title: "电压",
    width: 160,
    minWidth: 70,
    align: "left",
    sortable: true,
    visible: true,
  },
  {
    field: "attribute",
    title: "属性",
    width: 160,
    minWidth: 70,
    align: "left",
    sortable: true,
    visible: true,
  },
  {
    field: "fromQty",
    title: "需求数量",
    width: 160,
    minWidth: 70,
    align: "right",
    sortable: true,
    visible: true,
  },
  {
    field: "quoteQty",
    title: "可供货数量",
    width: 160,
    minWidth: 70,
    align: "right",
    sortable: true,
    visible: true,
  },
  {
    field: "qty",
    title: "中标数量",
    width: 160,
    minWidth: 70,
    align: "right",
    sortable: true,
    visible: true,
  },
  {
    field: "quotePrice",
    title: "报价单价(含税)",
    width: 160,
    minWidth: 70,
    align: "right",
    sortable: true,
    visible: true,
  },
  {
    field: "price",
    title: "中标含税单价",
    width: 160,
    minWidth: 70,
    align: "right",
    sortable: true,
    visible: true,
  },
  {
    field: "taxRate",
    title: "税率",
    width: 160,
    minWidth: 70,
    align: "right",
    sortable: true,
    visible: true,
  },
  {
    field: "untaxAmount",
    title: "不含税金额",
    width: 160,
    minWidth: 70,
    align: "right",
    sortable: true,
    visible: true,
  },
  {
    field: "amount",
    title: "含税金额",
    width: 160,
    minWidth: 70,
    align: "right",
    sortable: true,
    visible: true,
  },
  {
    field: "areaCodeListName",
    title: "收货区域",
    width: 160,
    minWidth: 70,
    align: "left",
    sortable: true,
    visible: true,
  },
  {
    field: "deliveryAddress",
    title: "收货地址",
    width: 160,
    minWidth: 70,
    align: "left",
    sortable: true,
    visible: true,
  },
  {
    field: "receiving",
    title: "收货人",
    width: 160,
    minWidth: 70,
    align: "left",
    sortable: true,
    visible: true,
  },
  {
    field: "receivingPhone",
    title: "收货电话",
    width: 160,
    minWidth: 70,
    align: "left",
    sortable: true,
    visible: true,
  }
];

[
  {
    label: "结果确认单号",
    field: "resultBillNo",
    type: "input",
    isDefault: true,
  },
  {
    label: "提交时间",
    fields: ["beginSubmissionTime", "endSubmissionTime"],
    type: "datePicker",
    isDefault: true,
  },
  {
    label: "审核时间",
    fields: ["beginAuditDate", "endAuditDate"],
    type: "datePicker",
    isDefault: true,
  },
  {
    label: "中标数量",
    fields: ["beginQty", "endQty"],
    type: "numberRange",
    isDefault: false,
  },
  {
    label: "询价单号",
    field: "enquiryBillNo",
    type: "input",
    isDefault: true,
  },
  {
    label: "询价项目名称",
    field: "projectName",
    type: "input",
    isDefault: false,
  },
  {
    label: "供应商名称",
    field: "businessLicense",
    type: "input",
    isDefault: false,
  },
  {
    label: "型号",
    field: "model",
    type: "input",
    isDefault: false,
  },
  {
    label: "规格",
    field: "standard",
    type: "input",
    isDefault: false,
  },
  {
    label: "电压",
    field: "voltageLevel",
    type: "input",
    isDefault: false,
  }
];
