[
  {
    field: "progress",
    title: "寻源进度",
    width: 190,
    minWidth: 70,
    resizable: false,
    fixed: "left",
    align: "left",
    sortable: true,
    visible: true,
  },
  
  {
    field: "type",
    title: "寻源方式",
    width: 190,
    minWidth: 70,
    align: "center",
    sortable: true,
    visible: true,
  },
  {
    field: "ly",
    title: "需求来源",
    width: 190,
    minWidth: 70,
    align: "center",
    sortable: true,
    visible: true,
  },
  {
    field: "name",
    title: "物品名称",
    minWidth: 70,
    align: "center",
    sortable: true,
    visible: true,
  },
  {
    field: 'ggxh',
    title: '规格型号', 
    width: 190, 
    minWidth: 70, 
    align: 'left', 
    sortable: true,
},
{
  field: 'qty',
  title: '申请数量', 
  width: 160, 
  minWidth: 70, 
  align: 'left', 
  sortable: true,
  visible: true,
},
{
  field: 'auditorName',
  title: '采购申请人', 
  width: 160, 
  minWidth: 70, 
  align: 'left', 
  sortable: true,
  visible: true,
},
{
  field: 'price',
  title: '预算单价(不含税)', 
  width: 160, 
  minWidth: 70, 
  align: 'left', 
  sortable: true,
  visible: true,
},
{
  field: 'amount',
  title: '不含税金额', 
  width: 160, 
  minWidth: 70, 
  align: 'left', 
  sortable: true,
  visible: true,
}
];