[
  {
    title: "选择",
    type: "checkbox",
    width: "80",
    align: "center",
    resizable: "true",
    minWidth: "80",
    visible: "true",
  },
  {
    field: "billNo",
    title: "需求池流水号",
    width: 190,
    minWidth: 70,
    resizable: false,
    align: "center",
    sortable: true,
    visible: true,
  },
  {
    field: "createUserName",
    title: "创建人",
    width: 160,
    minWidth: 70,
    align: "left",
    sortable: true,
  },
  {
    field: "createTime",
    title: "创建时间",
    width: 170,
    minWidth: 70,
    align: "center",
    sortable: true,
    visible: true,
  },
  {
    field: "updateUserName",
    title: "更新人",
    width: 170,
    minWidth: 70,
    align: "left",
    sortable: true,
    visible: true,
  },
  {
    field: "updateTime",
    title: "更新时间",
    width: 170,
    minWidth: 70,
    align: "center",
    sortable: true,
    visible: true,
  },
  {
    field: "billSourceName",
    title: "需求来源",
    width: 160,
    minWidth: 70,
    align: "left",
    sortable: true,
    visible: true,
  },
  {
    field: "projectName",
    title: "项目名称",
    width: 160,
    minWidth: 70,
    align: "left",
    sortable: true,
    visible: true,
  },
  {
    field: "fromBillNo",
    title: "申请单号",
    width: 160,
    minWidth: 70,
    align: "center",
    sortable: true,
    visible: true,
  },
  {
    field: "fromBillSubTime",
    title: "申请日期",
    width: 160,
    minWidth: 70,
    align: "center",
    sortable: true,
    visible: true,
  },
  {
    field: "fromBillCreateUserName",
    title: "申请人",
    width: 160,
    minWidth: 70,
    align: "left",
    sortable: true,
    visible: true,
  },
  {
    field: "purchaseDeptName",
    title: "采购部门",
    width: 160,
    minWidth: 70,
    align: "left",
    sortable: true,
    visible: true,
  },
  {
    field: "fromBillAmount",
    title: "申请金额",
    width: 160,
    minWidth: 70,
    align: "right",
    sortable: true,
    visible: true,
  },
  {
    field: "purchaseRequestDescription",
    title: "采购申请说明",
    width: 160,
    minWidth: 70,
    align: "left",
    sortable: true,
    visible: true,
  },
  {
    field: "createUserName",
    title: "寻源方式",
    width: 160,
    minWidth: 70,
    align: "left",
    sortable: true,
    visible: true,
  },
  {
    field: "sourcingBillNo",
    title: "寻源单据编号",
    width: 160,
    minWidth: 70,
    align: "center",
    sortable: true,
    visible: true,
  },
  {
    field: "confirmedSupplierName",
    title: "确认供应商名称",
    width: 160,
    minWidth: 70,
    align: "left",
    sortable: true,
    visible: true,
  },
  {
    field: "bidSegmentName",
    title: "标段名称",
    width: 160,
    minWidth: 70,
    align: "left",
    sortable: true,
    visible: true,
  },
  {
    field: "bidSegmentRemark",
    title: "标段说明",
    width: 160,
    minWidth: 70,
    align: "left",
    sortable: true,
    visible: true,
  },
  {
    field: "qty",
    title: "采购数量",
    width: 160,
    minWidth: 70,
    align: "right",
    sortable: true,
    visible: true,
  },
  {
    field: "totalApplicationAmount",
    title: "预算总金额",
    width: 160,
    minWidth: 70,
    align: "right",
    sortable: true,
    visible: true,
  },
  {
    field: "materialName",
    title: "采购商品",
    width: 160,
    minWidth: 70,
    align: "left",
    sortable: true,
    visible: true,
  },
  {
    field: "model",
    title: "型号",
    width: 160,
    minWidth: 70,
    align: "left",
    sortable: true,
    visible: true,
  },
  {
    field: "standard",
    title: "规格",
    width: 160,
    minWidth: 70,
    align: "left",
    sortable: true,
    visible: true,
  },
  {
    field: "voltageLevel",
    title: "电压",
    width: 160,
    minWidth: 70,
    align: "left",
    sortable: true,
    visible: true,
  },
  {
    field: "applicationQty",
    title: "申请数量",
    width: 160,
    minWidth: 70,
    align: "right",
    sortable: true,
    visible: true,
  },
  {
    field: "price",
    title: "预算单价(含税)",
    width: 160,
    minWidth: 70,
    align: "right",
    sortable: true,
    visible: true,
  },
  {
    field: "untaxPrice",
    title: "预算单价(不含税)",
    width: 160,
    minWidth: 70,
    align: "right",
    sortable: true,
    visible: true,
  },
  {
    field: "taxRate",
    title: "税率",
    width: 160,
    minWidth: 70,
    align: "right",
    sortable: true,
    visible: true,
  },
  {
    field: "untaxAmount",
    title: "不含税金额",
    width: 160,
    minWidth: 70,
    align: "right",
    sortable: true,
    visible: true,
  },
  {
    field: "amount",
    title: "含税金额",
    width: 160,
    minWidth: 70,
    align: "right",
    sortable: true,
    visible: true,
  },
  {
    field: "untaxPurchasePrice",
    title: "核价单价(不含税)",
    width: 160,
    minWidth: 70,
    align: "right",
    sortable: true,
    visible: true,
  },
  {
    field: "latestArrivalDate",
    title: "最晚到货时间",
    width: 160,
    minWidth: 70,
    align: "center",
    sortable: true,
    visible: true,
  },
  {
    field: "orderedQty",
    title: "已下单数量",
    width: 160,
    minWidth: 70,
    align: "right",
    sortable: true,
    visible: true,
  },
  {
    field: "unorderedQty",
    title: "未下单数量",
    width: 160,
    minWidth: 70,
    align: "right",
    sortable: true,
    visible: true,
  },
  {
    field: "contractBillNo",
    title: "合同单号",
    width: 160,
    minWidth: 70,
    align: "center",
    sortable: true,
    visible: true,
  },
];

// [
//   {
//     label: "需求池流水号",
//     field: "billNo",
//     type: "input",
//     isDefault: true,
//   },
//   {
//     label: "申请单号",
//     field: "fromBillNo",
//     type: "input",
//     isDefault: true,
//   },
//   {
//     label: '申请日期',
//     fields: ['beginSubmissionTime', 'endSubmissionTime'],
//     type: 'datePicker',
//     isDefault: true,
//   },
//   {
//     label: "申请人",
//     field: "createUserName",
//     type: "input",
//     isDefault: true,
//   },
//   {
//     label: "所属部门",
//     field: "purchaseDeptName",
//     type: "input",
//     isDefault: false,
//   },
//   {
//     label: "申请金额",
//     fields: ["beginFromBillAmount", "endFromBillAmount"],
//     type: "numberRange",
//     isDefault: false,
//   },
//     {
//     label: "寻源方式",
//     field: "sourcingMethodList",
//     type: "selectmulti",
//     isDefault: false,
//     source: "sourcingMethodList",
//     output: "string",
//   },
//   {
//     label: "寻源进度",
//     field: "sourcingStateList",
//     type: "selectmulti",
//     isDefault: false,
//     source: "sourcingStateList",
//     output: "string",
//   },
//   {
//     label: "寻源单据编号",
//     field: "sourcingBillNo",
//     type: "input",
//     isDefault: false,
//   },
//   {
//     label: "采购数量",
//     fields: ["beginQty", "endQty"],
//     type: "numberRange",
//     isDefault: false,
//   },
//   {
//     label: "确认供应商名称",
//     field: "confirmedSupplierName",
//     type: "input",
//     isDefault: false,
//   },

//   {
//     label: '最晚到货时间',
//     fields: ['beginLatestArrivalDate', 'endLatestArrivalDate'],
//     type: 'datePicker',
//     isDefault: false,
//   },
//   {
//     label: "采购商品",
//     field: "materialName",
//     type: "input",
//     isDefault: false,
//   },

//   {
//     label: '型号',
//     field: "model",
//     type: 'input',
//     isDefault: false,
//   },

//   {
//     label: "标段名称",
//     field: "bidSegmentName",
//     type: "input",
//     isDefault: false,
//   }
// ]

// new search 采购需求池
[
  { "label": "物料编码", "field": "materialCode", "type": "input", "isDefault": true },
  { "label": "物料名称", "field": "materialName", "type": "input", "isDefault": true },
  { "label": "物料分类", "field": "materialTypeName", "type": "input", "isDefault": true },
  { "label": "型号", "field": "model", "type": "input", "isDefault": true },
  { "label": "规格", "field": "standard", "type": "input" },
  { "label": "采购需求单号", "field": "purchNormalBillNo", "type": "input" },
  { "label": "是否紧急", "field": "urgentFlag", "type": "select", "source": "urgentFlag", "output": "string" },
  { "label": "需求类型", "field": "purchaseTypeName", "type": "selectmulti", "source": "purchaseTypeName", "output": "string" },
  { "label": "是否匹配价格库", "field": "matchPriceFlag", "type": "input" },
  { "label": "采购数量", "field": "qty", "type": "numberRange", "fields": ["beginQty", "endQty"] },
  { "label": "申请部门", "field": "purchaseDeptName", "type": "selectmulti", "source": "purchaseDeptName", "output": "string" }
]

// new table 采购需求池
[
  { "title": "选择", "type": "checkbox", "width": "80", "align": "center", "minWidth": "80" },
  { "field": "billNo", "title": "需求池流水号", "width": 190, "minWidth": 100, "align": "left" },
  { "field": "materialCode", "title": "物料编码", "width": 190, "minWidth": 100, "align": "left" },
  { "field": "materialName", "title": "物料名称", "width": 190, "minWidth": 100, "align": "left" },
  { "field": "materialTypeName", "title": "物料分类", "width": 190, "minWidth": 100, "align": "left" },
  { "field": "model", "title": "型号", "width": 120, "minWidth": 100, "align": "left" },
  { "field": "standard", "title": "规格", "width": 120, "minWidth": 100, "align": "left" },
  { "field": "voltageLevel", "title": "电压", "width": 120, "minWidth": 100, "align": "left" },
  { "field": "attribute", "title": "属性", "width": 120, "minWidth": 100, "align": "left" },
  { "field": "purchNormalBillNo", "title": "采购需求单号", "width": 150, "minWidth": 100, "align": "left" },
  { "field": "projectBillNo", "title": "项目编码", "width": 150, "minWidth": 100, "align": "left" },
  { "field": "projectName", "title": "项目名称", "width": 150, "minWidth": 100, "align": "left" },
  { "field": "urgentFlag", "title": "是否紧急", "width": 80, "minWidth": 80, "align": "center", "slots": { "default": "urgentFlag" } },
  { "field": "purchaseTypeName", "title": "需求类型", "width": 120, "minWidth": 100, "align": "left" },
  { "field": "purchNormalName", "title": "采购需求名称", "width": 120, "minWidth": 100, "align": "left" },
  { "field": "sourceStateName", "title": "寻源情况", "width": 120, "minWidth": 100, "align": "left", "sortable": true, "visible": true, "slots": { "default": "sourceState" } },
  { "field": "matchPriceFlag", "title": "是否匹配价格库", "width": 80, "minWidth": 80, "align": "center", "slots": { "default": "matchPriceFlag" } },
  { "field": "qty", "title": "需求数量", "width": 100, "minWidth": 100, "align": "left" },
  { "field": "pendingQty", "title": "待处理数量", "width": 100, "minWidth": 100, "align": "left" },
  { "field": "unit", "title": "单位", "width": 100, "minWidth": 100, "align": "left" },
  { "field": "createUserName", "title": "申请人", "width": 120, "minWidth": 100, "align": "left" },
  { "field": "purchaseDeptName", "title": "申请部门", "width": 120, "minWidth": 100, "align": "left" },
  { "field": "employDeptName", "title": "使用部门", "width": 120, "minWidth": 100, "align": "left" },
  { "field": "deliveryAddress", "title": "收货地址", "width": 150, "minWidth": 100, "align": "left", "slots": { "default": "deliveryAddress" } }
]


