[
  {
    field: "title",
    title: "公告标题",
    minWidth: 70,
    resizable: false,
    fixed: "left",
    align: "left",
    sortable: true,
    visible: true,
  },
  {
    field: "releaseEngineer",
    title: "发布人员",
    width: 190,
    minWidth: 70,
    align: "left",
    sortable: true,
    visible: true,
  },
  {
    field: "releaseTime",
    title: "发布时间",
    width: 190,
    minWidth: 70,
    align: "left",
    sortable: true,
    visible: true,
  },
  {
    field: "receivingPersonnel",
    title: "接收人员",
    width: 190,
    minWidth: 70,
    align: "left",
    sortable: true,
  },
  {
    field: "numberViews",
    title: "浏览次数",
    width: 190,
    minWidth: 70,
    align: "left",
    sortable: true,
  },
  {
    field: "deadline",
    title: "公示截止时间",
    width: 190,
    minWidth: 70,
    align: "left",
    sortable: true,
  },
  {
    field: "noticeState",
    title: "公告状态",
    width: 190,
    minWidth: 70,
    align: "left",
    sortable: true,
  },
  {
    field: "cz",
    title: "操作",
    width: 190,
    minWidth: 70,
    align: "left",
    sortable: true,
    visible: true,
    slots: { default: "cz" },
  },
];
[
  {
    field: "title",
    title: "公告标题",
    minWidth: 70,
    resizable: false,
    fixed: "left",
    align: "left",
    sortable: true,
    visible: true,
  },
  {
    field: "releaseEngineer",
    title: "发布人员",
    width: 190,
    minWidth: 70,
    align: "left",
    sortable: true,
    visible: true,
  },
  {
    field: "releaseTime",
    title: "发布时间",
    width: 190,
    minWidth: 70,
    align: "left",
    sortable: true,
    visible: true,
  },
  {
    field: "receivingPersonnel",
    title: "接收人员",
    width: 190,
    minWidth: 70,
    align: "left",
    sortable: true,
  },
  {
    field: "numberViews",
    title: "浏览次数",
    width: 190,
    minWidth: 70,
    align: "left",
    sortable: true,
  },

  {
    field: "cz",
    title: "操作",
    width: 190,
    minWidth: 70,
    align: "left",
    sortable: true,
    visible: true,
    slots: { default: "cz" },
  },
];

[
  {
    label: "公告标题",
    field: "title",
    type: "input",
    isDefault: true,
  },
  {
    label: "发布人员",
    field: "releaseEngineer",
    type: "input",
    isDefault: true,
  },
  {
    label: "接收人员",
    field: "receivingPersonnel",
    type: "input",
    isDefault: true,
  },
  {
    label: "发布时间",
    fields: ["beginReleaseTime", "endReleaseTime"],
    type: "datePicker",
    isDefault: true,
  },
];
