[
  {
    field: "billNo",
    title: "流水号",
    width: 190,
    minWidth: 70,
    resizable: false,
    fixed: "left",
    align: "left",
    sortable: true,
    visible: true,
  },
  {
    field: "createUserName",
    title: "创建人",
    width: 160,
    minWidth: 70,
    align: "left",
    sortable: true,
  },
  {
    field: "createTime",
    title: "单据时间",
    width: 170,
    minWidth: 70,
    align: "left",
    sortable: true,
    visible: true,
  },
  {
    field: "submissionTime",
    title: "提交时间",
    width: 170,
    minWidth: 70,
    align: "left",
    sortable: true,
    visible: true,
  }
  ,
  {
    field: "auditorName",
    title: "审核人",
    width: 170,
    minWidth: 70,
    align: "left",
    sortable: true,
    visible: true,
  },
  {
    field: "auditDate",
    title: "审核时间",
    width: 170,
    minWidth: 70,
    align: "left",
    sortable: true,
    visible: true,
  },
  {
    field: "enquiryBillNo",
    title: "询价单号",
    width: 160,
    minWidth: 70,
    align: "left",
    sortable: true,
    visible: true,
  },
  {
    field: "quoteBillNo",
    title: "报价单号",
    width: 160,
    minWidth: 70,
    align: "left",
    sortable: true,
    visible: true,
  },
  {
    field: "requirementsBillNo",
    title: "需求池流水号",
    width: 160,
    minWidth: 70,
    align: "left",
    sortable: true,
    visible: true,
  },
  {
    field: "supplierBillNo",
    title: "供应商编码",
    width: 160,
    minWidth: 70,
    align: "left",
    sortable: true,
    visible: true,
  },
  {
    field: "projectName",
    title: "项目名称",
    width: 160,
    minWidth: 70,
    align: "left",
    sortable: true,
    visible: true,
  },
  {
    field: "businessLicense",
    title: "供应商名称",
    width: 160,
    minWidth: 70,
    align: "left",
    sortable: true,
    visible: true,
  },
  {
    field: "purchNormalBillNo",
    title: "采购申请订单号",
    width: 160,
    minWidth: 70,
    align: "left",
    sortable: true,
    visible: true,
  },
  {
    field: "deadlineQuoteDate",
    title: "报价截止时间",
    width: 160,
    minWidth: 70,
    align: "left",
    sortable: true,
    visible: true,
  },
  {
    field: "materialName",
    title: "物品名称",
    width: 160,
    minWidth: 70,
    align: "left",
    sortable: true,
    visible: false,
  },
  {
    field: "model",
    title: "型号",
    width: 160,
    minWidth: 70,
    align: "left",
    sortable: true,
    visible: true,
  },
  {
    field: "standard",
    title: "规格",
    width: 160,
    minWidth: 70,
    align: "left",
    sortable: true,
    visible: true,
  },
  {
    field: "voltageLevel",
    title: "电压",
    width: 160,
    minWidth: 70,
    align: "left",
    sortable: true,
    visible: true,
  },
  {
    field: "fromQty",
    title: "需求数量",
    width: 160,
    minWidth: 70,
    align: "right",
    sortable: true,
    visible: true,
  },
  {
    field: "quoteQty",
    title: "可供货数量",
    width: 160,
    minWidth: 70,
    align: "right",
    sortable: true,
    visible: true,
  },
  {
    field: "quotePrice",
    title: "报价单价(含税)",
    width: 160,
    minWidth: 70,
    align: "right",
    sortable: true,
    visible: true,
  },
  {
    field: "taxRate",
    title: "税率",
    width: 160,
    minWidth: 70,
    align: "right",
    sortable: true,
    visible: true,
  },
  {
    field: "currentEnquiryTimes",
    title: "本次询价轮次",
    width: 160,
    minWidth: 70,
    align: "left",
    sortable: true,
    visible: true,
  },
  {
    field: "quoteFlagName",
    title: "参与报价",
    width: 160,
    minWidth: 70,
    align: "left",
    sortable: true,
    visible: true,
  },
];

[
  {
    label: "询价单号",
    field: "billNo",
    type: "input",
    isDefault: true,
  },
  {
    label: "提交时间",
    fields: ["beginSubmissionTime", "endSubmissionTime"],
    type: "datePicker",
    isDefault: true,
  },
  {
    label: "项目名称",
    field: "projectName",
    type: "input",
    isDefault: true,
  },
  {
    label: "供应商名称",
    field: "businessLicense",
    type: "input",
    isDefault: true,
  },
  {
    label: "报价截止时间",
    fields: ["beginDeadlineQuoteDate", "endDeadlineQuoteDate"],
    type: "datePicker",
    isDefault: false,
  },
  {
    label: "型号",
    field: "modal",
    type: "input",
    isDefault: false,
  },
  {
    label: "规格",
    field: "standard",
    type: "input",
    isDefault: false,
  },
  {
    label: "电压",
    field: "voltageLevel",
    type: "input",
    isDefault: false,
  },
];
