[
  {
    field: "billStateName",
    title: "单据状态",
    width: 100,
    minWidth: 100,
    resizable: false,
    fixed: "right",
    align: "center",
    sortable: true,
    slots: { default: "billState" },
    visible: true,
  },
  {
    field: "billNo",
    title: "申请单号",
    width: 190,
    minWidth: 70,
    resizable: false,
    fixed: "left",
    align: "left",
    sortable: true,
    visible: true,
  },
  {
    field: "createTime",
    title: "单据时间",
    width: 170,
    minWidth: 70,
    align: "center",
    sortable: true,
    visible: true,
  },
  {
    field: "submissionTime",
    title: "提交时间",
    width: 170,
    minWidth: 70,
    align: "center",
    sortable: true,
    visible: true,
  },
  {
    field: "auditDate",
    title: "审核时间",
    width: 170,
    minWidth: 70,
    align: "center",
    sortable: true,
    visible: true,
  },
  {
    field: 'createUserName',
    title: '创建人', 
    width: 160, 
    minWidth: 70, 
    align: 'left', 
    sortable: true,
},
{
  field: 'auditorName',
  title: '审核人', 
  width: 160, 
  minWidth: 70, 
  align: 'left', 
  sortable: true,
  visible: true,
},
{
  field: 'auditorName',
  title: '采购申请人', 
  width: 160, 
  minWidth: 70, 
  align: 'left', 
  sortable: true,
  visible: true,
},
{
  field: 'createUserName',
  title: '采购申请日期', 
  width: 160, 
  minWidth: 70, 
  align: 'left', 
  sortable: true,
  visible: true,
},
{
  field: 'createUserName',
  title: '采购部门', 
  width: 160, 
  minWidth: 70, 
  align: 'left', 
  sortable: true,
  visible: true,
},
{
  field: 'createUserName',
  title: '申请公司', 
  width: 160, 
  minWidth: 70, 
  align: 'left', 
  sortable: true,
  visible: true,
},
{
  field: 'createUserName',
  title: '采购预算金额', 
  width: 160, 
  minWidth: 70, 
  align: 'left', 
  sortable: true,
  visible: true,
},
{
  field: 'createUserName',
  title: '采购申请说明', 
  width: 160, 
  minWidth: 70, 
  align: 'left', 
  sortable: true,
  visible: true,
},
{
  field: 'createUserName',
  title: '寻源方式', 
  width: 160, 
  minWidth: 70, 
  align: 'left', 
  sortable: true,
  visible: true,
},
{
  field: 'createUserName',
  title: '供应商', 
  width: 160, 
  minWidth: 70, 
  align: 'left', 
  sortable: true,
  visible: true,
},
{
  field: 'createUserName',
  title: '确认供应商名称', 
  width: 160, 
  minWidth: 70, 
  align: 'left', 
  sortable: true,
  visible: false,
},
{
  field: 'createUserName',
  title: '询价进度', 
  width: 160, 
  minWidth: 70, 
  align: 'left', 
  sortable: true,
  visible: false,
},
{
  field: 'createUserName',
  title: '采购进度', 
  width: 160, 
  minWidth: 70, 
  align: 'left', 
  sortable: true,
  visible: false,
}
];


[
  {
    title: "选择",
    type: "checkbox",
    width: "80",
    align: "center",
    resizable: "true",
    minWidth: "80",
    visible: "true",
  },
  {
    field: "materialName",
    title: "采购商品",
    width: 190,
    minWidth: 70,
    resizable: false,
    align: "left",
    sortable: true,
    visible: true,
  },
  {
    field: "materialTypeName",
    title: "物料类型",
    width: 190,
    minWidth: 70,
    resizable: false,
    align: "left",
    sortable: true,
    visible: true,
  },
  {
    field: "materialCode",
    title: "物料编码",
    width: 190,
    minWidth: 70,
    resizable: false,
    align: "left",
    sortable: true,
    visible: true,
  },
  {
    field: "model",
    title: "型号",
    width: 190,
    minWidth: 70,
    resizable: false,
   
    align: "left",
    sortable: true,
    visible: true,
  },
  {
    field: "standard",
    title: "规格",
    width: 190,
    minWidth: 70,
    resizable: false,
   
    align: "left",
    sortable: true,
    visible: true,
  },
  {
    field: "voltageLevel",
    title: "电压",
    width: 190,
    minWidth: 70,
    resizable: false,
   
    align: "left",
    sortable: true,
    visible: true,
  },
  {
    field: "attribute",
    title: "属性",
    width: 190,
    minWidth: 70,
    resizable: false,
    align: "left",
    sortable: true,
    visible: true,
  },
  {
    field: "unit",
    title: "单位",
    width: 190,
    minWidth: 70,
    resizable: false,
    align: "left",
    sortable: true,
    visible: true,
  },
  {
    field: "qty",
    title: "申请数量",
    width: 190,
    minWidth: 70,
    resizable: false,
    align: "left",
    sortable: true,
    visible: true,
    slots: { default: "slot_edit_integerNumber" },
  },
  {
    field: "untaxPrice",
    title: "预算单价(不含税)",
    width: 190,
    minWidth: 70,
    resizable: false,
   
    align: "left",
    sortable: true,
    visible: true,
  },
  {
    field: "taxRate",
    title: "税率",
    width: 190,
    minWidth: 70,
    resizable: false,
   
    align: "left",
    sortable: true,
    visible: true,
    params: {
      displayDigits: 2,
    },
    slots: { default: "slot_edit_number" },
  },
  {
    field: "price",
    title: "预算单价(含税)",
    width: 190,
    minWidth: 70,
    resizable: false,
   
    align: "left",
    sortable: true,
    visible: true,
  },
  {
    field: "untaxAmount",
    title: "预算金额(不含税)",
    width: 190,
    minWidth: 70,
    resizable: false,
   
    align: "left",
    sortable: true,
    visible: true,
  },
  {
    field: "amount",
    title: "预算金额(含税)",
    width: 190,
    minWidth: 70,
    resizable: false,
   
    align: "left",
    sortable: true,
    visible: true,
  },
  {
    field: "latestArrivalDate",
    title: "最晚到货时间",
    width: 190,
    minWidth: 70,
    resizable: false,
    align: "left",
    sortable: true,
    visible: true,
    slots: { default: "slot_edit_date" },
  },

]