// [
//   {
//     field: "billStateName",
//     title: "单据状态",
//     width: 100,
//     minWidth: 100,
//     resizable: false,
//     fixed: "right",
//     align: "center",
//     sortable: true,
//     slots: { default: "billState" },
//     visible: true,
//   },
//   {
//     field: "billNo",
//     title: "申请单号",
//     width: 190,
//     minWidth: 70,
//     resizable: false,
//     align: "left",
//     sortable: true,
//     visible: true,
//   },
//   {
//     field: 'createUserName',
//     title: '创建人', 
//     width: 160, 
//     minWidth: 70, 
//     align: 'left', 
//     sortable: true,
// },
//   {
//     field: "createTime",
//     title: "单据时间",
//     width: 170,
//     minWidth: 70,
//     align: "center",
//     sortable: true,
//     visible: true,
//   },
//   {
//     field: "submissionTime",
//     title: "提交时间",
//     width: 170,
//     minWidth: 70,
//     align: "center",
//     sortable: true,
//     visible: true,
//   },
//   {
//     field: "auditDate",
//     title: "审核时间",
//     width: 170,
//     minWidth: 70,
//     align: "center",
//     sortable: true,
//     visible: true,
//   },

// {
//   field: 'auditorName',
//   title: '审核人', 
//   width: 160, 
//   minWidth: 70, 
//   align: 'left', 
//   sortable: true,
//   visible: true,
// },
// {
//   field: 'projectName',
//   title: '项目名称', 
//   width: 160, 
//   minWidth: 70, 
//   align: 'left', 
//   sortable: true,
//   visible: true,
// },
// {
//   field: 'approvalDate',
//   title: '立项日期', 
//   width: 160, 
//   minWidth: 70, 
//   align: 'left', 
//   sortable: true,
//   visible: true,
// },
// {
//   field: 'purchaseSubUserName',
//   title: '申请人', 
//   width: 160, 
//   minWidth: 70, 
//   align: 'left', 
//   sortable: true,
//   visible: true,
// },
// {
//   field: 'purchaseDeptName',
//   title: '立项部门', 
//   width: 160, 
//   minWidth: 70, 
//   align: 'left', 
//   sortable: true,
//   visible: true,
// },
// {
//   field: 'amount',
//   title: '采购预算金额', 
//   width: 160, 
//   minWidth: 70, 
//   align: 'left', 
//   sortable: true,
//   visible: true,
// },
// {
//   field: 'purchaseRequestDescription',
//   title: '立项申请说明', 
//   width: 160, 
//   minWidth: 70, 
//   align: 'left', 
//   sortable: true,
//   visible: true,
// },
// {
//   field: 'sourcingMethodName',
//   title: '寻源方式', 
//   width: 160, 
//   minWidth: 70, 
//   align: 'left', 
//   sortable: true,
//   visible: true,
// },
// {
//   field: 'isBidSegmentName',
//   title: '标段', 
//   width: 160, 
//   minWidth: 70, 
//   align: 'left', 
//   sortable: true,
//   visible: true,
// },
// {
//   field: 'sourcingStateName',
//   title: '寻源进度', 
//   width: 160, 
//   minWidth: 70, 
//   align: 'left', 
//   sortable: true,
//   visible: false,
// }
// ];


// [
//   {
//     label: "申请单号",
//     field: "billNo",
//     type: "input",
//     isDefault: true,
//   },
//   {
//     label: "单据状态",
//     field: "billStateList",
//     type: "selectmulti",
//     isDefault: true,
//     source: "statelist",
//     output: "string",
//   },
//   {
//     label: '单据时间',
//     fields: ['beginCreateTime', 'endCreateTime'],
//     type: 'datePicker',
//     isDefault: true,
//   },
//   {
//     label: '提交时间',
//     fields: ['beginSubmissionTime', 'endSubmissionTime'],
//     type: 'datePicker',
//     isDefault: true,
//   },
//   {
//     label: '审核时间',
//     fields: ['beginAuditDate', 'endAuditDate'],
//     type: 'datePicker',
//     isDefault: false,
//   },
//   {
//     label: "申请人",
//     field: "createUserName",
//     type: "input",
//     isDefault: false,
//   },
//   {
//     label: "审核人",
//     field: "auditorName",
//     type: "input",
//     isDefault: false,
//   },
//   {
//     label: "采购申请人",
//     field: "purchaseSubUserName",
//     type: "input",
//     isDefault: false,
//   },
//   {
//     label: "项目名称",
//     field: "projectName",
//     type: "input",
//     isDefault: false,
//   },
//   {
//     label: "立项部门",
//     field: "purchaseDeptName",
//     type: "input",
//     isDefault: false,
//   },
//   {
//     label: '项目立项日期',
//     fields: ['beginApprovalDate', 'endApprovalDate'],
//     type: 'datePicker',
//     isDefault: false,
//   },
//   {
//     label: "采购预算金额",
//     fields: ["beginAmount", "endAmount"],
//     type: "numberRange",
//     isDefault: false,
//   },
// ]