// [
//   {
//     label: "需求来源",
//     field: "dataSourceName",
//     type: "",
//     width: "33%",
//     required: true,
//   },
//   {
//     label: "申请单号",
//     field: "fromBillNo",
//     required: true,
//     type: "",
//     width: "33%",
//   },
//   {
//     label: "申请日期",
//     field: "submissionTime",
//     required: true,
//     type: "",
//     width: "33%",
//   },
//   {
//     label: "申请人",
//     field: "purchaseSubUserName",
//     required: true,
//     type: "",
//     width: "33%",
//   },
//   {
//     label: "所属部门",
//     field: "purchaseDeptName",
//     required: true,
//     type: "",
//     width: "33%",
//   },
//   {
//     label: "申请金额",
//     field: "fromBillAmount",
//     type: "",
//     digits: 2,
//     precision: 2,
//     formatterName: "toFixedNumber",
//     width: "33%",
//   },
//   {
//     label: "采购申请说明",
//     field: "purchaseRequestDescription",
//     required: true,
//     type: "",
//     width: "33%",
//   }
// ];

// [
//   {
//     label: "预算总金额",
//     field: "totalApplicationAmount",
//     type: "",
//     width: "33%",
//     required: true,
//   },
//   {
//     label: "采购商品",
//     field: "materialName",
//     required: true,
//     type: "",
//     width: "33%",
//   },
//   {
//     label: "型号",
//     field: "model",
//     required: true,
//     type: "",
//     width: "33%",
//   },
//   {
//     label: "规格",
//     field: "standard",
//     required: true,
//     type: "",
//     width: "33%",
//   },
//   {
//     label: "电压",
//     field: "voltageLevel",
//     required: true,
//     type: "",
//     width: "33%",
//   },
//   {
//     label: "属性",
//     field: "attribute",
//     required: true,
//     type: "",
//     width: "33%",
//   },
//   {
//     label: "申请数量",
//     field: "qty",
//     type: "number",
//     digits: 3,
//     precision: 3,
//     formatterName: "toFixedNumber",
//     width: "33%",
//   },
//   {
//     label: "预算单价(不含税)",
//     field: "untaxPrice",
//     type: "",
//     digits: 2,
//     precision: 2,
//     formatterName: "toFixedNumber",
//     width: "33%",
//   },
//   {
//     label: "预算单价(含税)",
//     field: "price",
//     type: "",
//     digits: 2,
//     precision: 2,
//     formatterName: "toFixedNumber",
//     width: "33%",
//   },
//   {
//     label: "税率",
//     field: "taxRate",
//     type: "",
//     digits: 2,
//     precision: 2,
//     formatterName: "toFixedNumber",
//     width: "33%",
//   },
//   {
//     label: "不含税金额",
//     field: "untaxAmount",
//     type: "",
//     digits: 2,
//     precision: 2,
//     formatterName: "toFixedNumber",
//     width: "33%",
//   },
//   {
//     label: "含税金额",
//     field: "amount",
//     type: "",
//     digits: 2,
//     precision: 2,
//     formatterName: "toFixedNumber",
//     width: "33%",
//   },
//   {
//     label: "最晚到货时间",
//     field: "latestArrivalDate",
//     type: "",
//     width: "33%",
//   },
//   {
//     label: "标段名称",
//     field: "bidSegmentName",
//     type: "",
//     width: "33%",
//   },
//   {
//     label: "标段说明",
//     field: "bidSegmentRemark",
//     type: "",
//     width: "33%",
//   }
// ];


// [
//   {
//     label: "寻源方式",
//     field: "sourcingMethod",
//     required: true,
//     type: "selectinput",
//     source: "sourcingMethodList",
//     width: "33%",
//   },
//   {
//     label: "寻源进度",
//     field: "sourcingState",
//     required: true,
//     type: "selectinput",
//     source: "sourcingStateList",
//     width: "33%",
//   },
//   {
//     label: "寻源单据编号",
//     field: "sourcingBillNo",
//     type: "",
//     width: "33%",
//   }
//   ,
//   {
//     label: "供应商名称",
//     field: "supplierList",
//     type: "",
//     width: "33%",
//   } ,
//   {
//     label: "确认供应商名称",
//     field: "confirmedSupplierName",
//     type: "",
//     width: "33%",
//   },
//   {
//     label: "采购数量",
//     field: "qty",
//     type: "number",
//     digits: 2,
//     precision: 2,
//     formatterName: "toFixedNumber",
//     width: "33%",
//   },
//   {
//     label: "核价单价(含税)",
//     field: "purchasePrice",
//     type: "number",
//     digits: 2,
//     precision: 2,
//     formatterName: "toFixedNumber",
//     width: "33%",
//   },
//   {
//     label: "核价单价(不含税)",
//     field: "untaxPurchasePrice",
//     type: "number",
//     digits: 2,
//     precision: 2,
//     formatterName: "toFixedNumber",
//     width: "33%",
//   },
// ]


// [
//   {
//     label: "已下单数量",
//     field: "orderedQty",
//     type: "number",
//     digits: 2,
//     precision: 2,
//     formatterName: "toFixedNumber",
//     width: "33%",
//   },
//   {
//     label: "未下单数量",
//     field: "unorderedQty",
//     type: "",
//     digits: 2,
//     precision: 2,
//     formatterName: "toFixedNumber",
//     width: "33%",
//   },
//   {
//     label: "合同单号",
//     field: "contractBillNo",
//     type: "input",
//     width: "33%",
//   }
// ]